### ISSUE TITLE
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged!

### ISSUE THREAD

**Issue by steve47457** [AppIntro/AppIntro#1083]
This crash occurs sometimes, please update, thanks 😊 
Android version: multiple
Devices: multiple
AppIntro Version: 6.2.0

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mycompany.myapp/com.company.app.MyClass}: java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 2 Pager id: com.mycompany.myapp:id/view_pager Pager class: class com.github.appintro.internal.AppIntroViewPager Problematic adapter: class com.github.appintro.internal.viewpager.PagerAdapter
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3939)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4096)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6099)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5985)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2441)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8396)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

Caused by java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 2 Pager id: com.mycompany.myapp:id/view_pager Pager class: class com.github.appintro.internal.AppIntroViewPager Problematic adapter: class com.github.appintro.internal.viewpager.PagerAdapter
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:579)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:2)
       at androidx.viewpager.widget.ViewPager.setOffscreenPageLimit(ViewPager.java:40)
       at com.github.appintro.AppIntroBase.addSlide(AppIntroBase.java:44)
       at com.company.app.MyClass.myMethod(MyClass.java:18)
       at com.company.app.MyClass.onCreate(MyClass.java:69)
       at android.app.Activity.performCreate(Activity.java:8369)
       at android.app.Activity.performCreate(Activity.java:8347)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1379)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3912)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4096)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6099)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5985)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2441)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8396)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by cortinico** [comment]
Are you doing anything custom?
Can you share a reproducer?

**Comment by steve47457** [comment]
Hi @cortinico Thanks for replying! I'm not doing anything custom, and I'm not aware of the circumstances behind this crash and don't know how to reproduce it, unfortunately. I just know that half of the crashes occur in the background.

**Comment by cortinico** [comment]
It's really hard to fix then without a reproducer

**Comment by yarik1988** [comment]
I also encounter the same error (recorded using Crashlytics, Android 11, Intel Jasper Lake Chromebook)

**Comment by yarik1988** [comment]
It's happening not consistently, only couple of times. I ended up turning wizard mode off, so the line pager.offscreenPageLimit = fragments.size is not called

**Comment by paolorotolo** [comment]
This should be fixed in AppIntro 7.0.0 (Beta) which uses ViewPager2. Please feel free to reopen the issue if it still occurs. Thanks!
