### ISSUE TITLE
Getting Index out of bound exception

### ISSUE THREAD

**Issue by sanketkhote** [AppIntro/AppIntro#1099]
getting this error while running an app:
2023-06-18 19:17:28.468 21698-21698 AndroidRuntime          com.sanket.cashgrab                  E  FATAL EXCEPTION: main
                                                                                                    Process: com.sanket.cashgrab, PID: 21698
                                                                                                    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:437)
                                                                                                    	at com.github.appintro.internal.viewpager.PagerAdapter.getItem(PagerAdapter.kt:14)
                                                                                                    	at com.github.appintro.AppIntroBase.onPostCreate$lambda-2(AppIntroBase.kt:465)
                                                                                                    	at com.github.appintro.AppIntroBase.$r8$lambda$b19Ek5Zu9niZtxMl6o961wAzzv0(Unknown Source:0)
                                                                                                    	at com.github.appintro.AppIntroBase$$ExternalSyntheticLambda2.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

## 💣 Steps to reproduce
To reproduce:->
1. create an android project(java) -> extend Mainactivity with AppIntro
2. start intent to another activity before add slide
3. add some slides using add slide ((AppIntroFragment.createInstance)

## 📱 Tech info
 - AppIntro Version: 6.2.0
 - Device: samsung s21 plus
 - Android OS Version: 13

**Comment by cortinico** [comment]
> 3\. add some slides using add slide ((AppIntroFragment.createInstance)

I'm not able to reproduce. Could you provide a reproducer?

**Comment by paolorotolo** [comment]
Closing for inactivity
