### ISSUE TITLE
Sample App TODO (Ignore this)

### ISSUE THREAD

**Issue by Andrew-Quebe** [AppIntro/AppIntro#369]
1. Add animations demo
2. Add slide policy demo
3. Add Wizard mode demo

**Comment by avluis** [comment]
Ignoring...

**Comment by Andrew-Quebe** [comment]
Get translated strings from #291, #292, #321, #365, & #366.

**Comment by Andrew-Quebe** [comment]
Add icons to navigation drawer items

**Comment by avluis** [comment]
@Andrew-Quebe I'm not able to run the example app on my Nexus 6P (7.1.1 latest dev) -- is it not complete?
It's currently complaining about the fragment not being attached to an activity.
Note that this applies to the sample apk attached to the repo and the code itself when I build it.

Here is my logcat in relation to this:

```ruby
11-30 01:31:23.534 16633-16633/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.amqtech.opensource.appintroexample, PID: 16633
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amqtech.opensource.appintroexample/com.amqtech.opensource.appintroexample.ui.MainActivity}: java.lang.IllegalStateException: Fragment MainTabsFragment{50e1821} not attached to Activity
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: java.lang.IllegalStateException: Fragment MainTabsFragment{50e1821} not attached to Activity
                                                       at android.app.Fragment.getResources(Fragment.java:814)
                                                       at com.amqtech.opensource.appintroexample.ui.fragment.MainTabsFragment.<init>(MainTabsFragment.java:24)
                                                       at com.amqtech.opensource.appintroexample.ui.MainActivity$1.onItemClick(MainActivity.java:52)
                                                       at com.mikepenz.materialdrawer.DrawerBuilder.createContent(DrawerBuilder.java:1769)
                                                       at com.mikepenz.materialdrawer.DrawerBuilder.buildView(DrawerBuilder.java:1483)
                                                       at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1281)
                                                       at com.amqtech.opensource.appintroexample.ui.MainActivity.onCreate(MainActivity.java:74)
                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by Andrew-Quebe** [comment]
@avluis I'm running Android 7.1 on my Pixel, and everything works just fine for me. It may be something specific to 7.1.1. I'll do some testing.

**Comment by Andrew-Quebe** [comment]
Hmm...I just ran the app myself, and it's crashing for me too. I should run my apps more often :P

I basically broke something code wise without realizing it...fixing now...hopefully.

**Comment by Andrew-Quebe** [comment]
Adding #385 to this list.

**Comment by Anutha02** [comment]
Imma Do it

**Comment by cortinico** [comment]
Closing as the issue is stale
