### ISSUE TITLE
Android Version 7 java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by aknkaplanoglu** [AppIntro/AppIntro#408]
Hello,
I added 4 fragment and when clicking next button from 3rd fragment to 4th there was a java.lang.IndexOutOfBoundsException. Here is the stacktrace below:

```
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.get(ArrayList.java:411)
	at android.support.v4.view.ViewPager.getChildDrawingOrder(ViewPager.java:828)
	at android.view.View.populateAccessibilityNodeInfoDrawingOrderInParent(View.java:6966)
	at android.view.View.onInitializeAccessibilityNodeInfoInternal(View.java:6925)
	at android.view.ViewGroup.onInitializeAccessibilityNodeInfoInternal(ViewGroup.java:3106)
	at android.view.View$AccessibilityDelegate.onInitializeAccessibilityNodeInfo(View.java:23403)
	at android.support.v4.view.AccessibilityDelegateCompatIcs.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompatIcs.java:101)
	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:198)
	at android.support.v4.view.AccessibilityDelegateCompat.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:451)
	at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:56)
	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:246)
	at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompatJellyBean.java:66)
	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6539)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:6500)
	at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:23472)
	at android.view.View.createAccessibilityNodeInfo(View.java:6483)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
	at android.view.View.onInitializeAccessibilityEventInternal(View.java:6437)
	at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:23384)
	at android.support.v4.view.AccessibilityDelegateCompatIcs.onInitializeAccessibilityEvent(AccessibilityDelegateCompatIcs.java:97)
	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:192)
	at android.support.v4.view.AccessibilityDelegateCompat.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:432)
	at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityEvent(RecyclerViewAccessibilityDelegate.java:65)
	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:241)
	at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompatJellyBean.java:61)
	at android.view.View.onInitializeAccessibilityEvent(View.java:6423)
	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6290)
	at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:23323)
	at android.support.v4.view.AccessibilityDelegateCompatIcs.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatIcs.java:122)
	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:223)
	at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:371)
	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:268)
	at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatJellyBean.java:87)
	at android.view.View.sendAccessibilityEventUnchecked(View.java:6273)
	at android.support.v7.widget.RecyclerView.sendAccessibilityEventUnchecked(RecyclerView.java:3148)
	at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:23509)
	at android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost(View.java:23542)
	at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:9407)
	at android.view.View.onFocusChanged(View.java:6158)
	at android.view.View.clearFocusInternal(View.java:6062)
	at android.view.View.unFocus(View.java:6095)
	at android.view.ViewGroup.unFocus(ViewGroup.java:995)
	at android.view.ViewGroup.unFocus(ViewGroup.java:997)
	at android.view.ViewGroup.unFocus(ViewGroup.java:997)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4739)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4726)
	at android.view.ViewGroup.removeView(ViewGroup.java:4657)
	at android.support.v4.view.ViewPager.removeView(ViewPager.java:1527)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1406)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1523)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1598)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2145)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1969)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:620)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2150)
	at com.github.paolorotolo.appintro.AppIntroViewPager.onInterceptTouchEvent(AppIntroViewPager.java:62)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
	at com.github.paolorotolo.appintro.AppIntroBase.dispatchTouchEvent(AppIntroBase.java:184)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
	at android.view.View.dispatchPointerEvent(View.java:10163)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4421)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4289)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3836)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3889)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3855)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3982)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3863)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4039)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3836)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3889)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3855)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3863)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3836)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6197)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6171)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6132)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6300)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by avluis** [comment]
**AppIntro Version**:


**Device/Android Version**:


**Issue details / Repro steps / Use case background**: 


**Your Code**: 


**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by avluis** [comment]
```java
addSlide(SampleSlide.newInstance(R.layout.intro2,this));
addSlide(SampleSlide.newInstance(R.layout.intro3,this));
addSlide(SampleSlide.newInstance(R.layout.intro4,this));
```

Please take a look at the [README](https://github.com/apl-devs/AppIntro#basic-usage), should be the first section, which shows you how to use the library.

**Comment by aknkaplanoglu** [comment]
I know how to use this library. It does not run only on version 7. It is running for the other versions without a problem.  So your answer does not provide a solution.

**Comment by avluis** [comment]
I'm afraid you are skipping right over the area you need to look at -- take another look at the code you provided and the code that is shown on the README.
I run this library on an Android 7.1.1 device (Nexus 6P) so I know it works.

**Comment by aknkaplanoglu** [comment]
This is my SampleSlide.java:

```
public class SampleSlide extends Fragment {

    private static final String ARG_LAYOUT_RES_ID = "layoutResId";

    public static SampleSlide newInstance(int layoutResId, Context context) {

        Locale locale = new Locale(Preferences.getLanguageCode(context));
        Locale.setDefault(locale);
        Configuration config = new Configuration();
        config.locale = locale;
        context.getResources().updateConfiguration(config,
                context.getResources().getDisplayMetrics());

        SampleSlide sampleSlide = new SampleSlide();

        Bundle args = new Bundle();
        args.putInt(ARG_LAYOUT_RES_ID, layoutResId);
        sampleSlide.setArguments(args);

        return sampleSlide;
    }

    private int layoutResId;

    public SampleSlide() {}

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setLanguage();
        if(getArguments() != null && getArguments().containsKey(ARG_LAYOUT_RES_ID))
            layoutResId = getArguments().getInt(ARG_LAYOUT_RES_ID);
    }

    private void setLanguage() {
        Locale locale = new Locale(Preferences.getLanguageCode(getActivity()));
        Locale.setDefault(locale);
        Configuration config = new Configuration();
        config.locale = locale;
        getActivity().getResources().updateConfiguration(config,
                getActivity().getResources().getDisplayMetrics());
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(layoutResId, container, false);
    }

}
```

**Comment by kwinto93** [comment]
@aknkaplanoglu Wiki page: https://github.com/apl-devs/AppIntro/wiki/How-to-Use#show-the-intro-once is completely misleading, because there is:
`public onCreate` used twice, but `AppIntro` is based on `AppCompatActivity`, not regular `Activity`, so `public onCreate` is not being invoked.

Please use `protected onCreate` and check main readme: https://github.com/apl-devs/AppIntro#basic-usage mentioned previously by @avluis 

Have a nice day!

**Comment by lingyfh** [comment]
try setOffscreenPageLimit.

**Comment by yarkey09** [comment]
class CustomViewPager extend ViewPager {

    @Override
    protected int getChildDrawingOrder(int childCount, int i) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            try {
                Field DrawingOrderedChildrenField = ViewPager.class.getDeclaredField("mDrawingOrderedChildren");
                DrawingOrderedChildrenField.setAccessible(true);
                ArrayList mDrawingOrderedChildren = (ArrayList) DrawingOrderedChildrenField.get(this);

                if (mDrawingOrderedChildren == null || mDrawingOrderedChildren.size() != getChildCount()) {
                    Method SortChildDrawingOrderMethod = ViewPager.class.getDeclaredMethod("sortChildDrawingOrder");
                    SortChildDrawingOrderMethod.setAccessible(true);
                    SortChildDrawingOrderMethod.invoke(this);
                }
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            } catch (NoSuchFieldException e) {
                e.printStackTrace();
            }
        }

        return super.getChildDrawingOrder(childCount, i);
    }

}

try to fix the error by custom code ..

**Comment by Anutha02** [comment]
Is this issue still present?

**Comment by Anutha02** [comment]
@cortinico Should be closed for inactivity

**Comment by AnuthaDev** [comment]
@cortinico Please close this.

**Comment by vincentssn** [comment]
> > But it seems cause another prob that :
> 
> Hey @vincentssn,
> This issue is really old and has been closed 2 years ago. Can I ask you to create a new issue and provide a reproducer for your problem?

Hi, @cortinico 
Thanks for your reply. Sorry to bother you.
There is another similar prob in my proj, that I suspect it is cause by the fix from @yarkey09. 
If there is no the same prob happened in the proj with that fix. May I should consider the other reasons.
