### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by mveroukis** [AppIntro/AppIntro#419]
**AppIntro Version**: 4.1 or whatever the latest is right now
**Device/Android Version**:Emulator Android 6.0
**Issue details / Repro steps / Use case background**: 

I call AddSlide() in OnCreate (an activity that inherits from AppIntro). When the screen is rotated, I noticed the super.OnCreate() fires my fragment contructors AND I'm still calling AddSlide() in OnCreate. So the fragments are created twice. How can I prevent this? Can I check the bundle to ensure I don't re-create & add the fragments? Or is there a way to clean up my fragments when the host activity is destroyed (a counter to AddSlide? I don't see a RemoveSlide).

**Comment by sschueller** [comment]
I am also seeing out of memory errors every so often in my app. Here a trace from the play store. This one is from a device withe 2GB memory: Redmi Note 3 (kenzo). Most crashes are on Android 5.1.

I have 8 slides each with an image around 10k - 100k. Total 388K. Setting them in onCreate like the example:

```
addSlide(AppIntroFragment.newInstance(getString(R.string.intro_slide1_title),
                getString(R.string.intro_slide1_description), R.drawable.slide1, Color.parseColor("#121212")));
```

```
java.lang.OutOfMemoryError
com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView

java.lang.OutOfMemoryError: 
  at dalvik.system.VMRuntime.newNonMovableArray(Native Method:0)
  at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method:0)
  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:613)
  at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:446)
  at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
  at android.content.res.Resources.createFromResourceStream(Resources.java:2822)
  at android.content.res.Resources.loadDrawableForCookie(Resources.java:2523)
  at android.content.res.Resources.loadDrawable(Resources.java:2421)
  at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393)
  at android.content.res.Resources.getDrawable(Resources.java:805)
  at android.content.Context.getDrawable(Context.java:412)
  at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
  at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
  at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
  at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:73)
  at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:81)
  at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView(AppIntroBaseFragment.java:103)
  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
  at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
  at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
  at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
  at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
  at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
  at android.support.v4.view.ViewPager$3.run(ViewPager.java:277)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
  at android.view.Choreographer.doCallbacks(Choreographer.java:588)
  at android.view.Choreographer.doFrame(Choreographer.java:557)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:761)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5276)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

java.lang.OutOfMemoryError: 
  at dalvik.system.VMRuntime.newNonMovableArray(Native Method:0)
  at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method:0)
  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:613)
  at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:446)
  at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:973)
  at android.content.res.Resources.createFromResourceStream(Resources.java:2771)
  at android.content.res.Resources.loadDrawableForCookie(Resources.java:2472)
  at android.content.res.Resources.loadDrawable(Resources.java:2370)
  at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393)
  at android.content.res.Resources.getDrawable(Resources.java:776)
  at android.content.Context.getDrawable(Context.java:411)
  at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
  at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
  at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
  at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:73)
  at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:81)
  at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView(AppIntroBaseFragment.java:103)
  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
  at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
  at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
  at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
  at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
  at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:672)
  at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:634)
  at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:615)
  at com.github.paolorotolo.appintro.AppIntroViewPager.setCurrentItem(AppIntroViewPager.java:52)
  at com.github.paolorotolo.appintro.AppIntroBase$NextButtonOnClickListener.onClick(AppIntroBase.java:861)
  at android.view.View.performClick(View.java:4759)
  at android.view.View$PerformClick.run(View.java:19770)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5237)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by avluis** [comment]
I'm gonna have to see more code in order to address this one -- please contact me directly if you are having this issue and you wish to help address it (and don't mind sharing your code).

**Comment by nicolabeghin** [comment]
Issue seems related to < 6.0 Android, just got some of them in Android 4.4 (Genymotion emulator)

**Comment by nicolabeghin** [comment]
any update on this?

**Comment by Debdeep009** [comment]
Yes, I faced the same with android 4.3. Just happens when fragment is inflated.

**Comment by YoiYang** [comment]
Experiencing similar issue. 
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 53887692 byte allocation with 15443312 free bytes and 14MB until OOM
com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView
keyboard_arrow_down

**Comment by arutkayb** [comment]
Similar issue on Android 7.0 and 4.3

**Comment by cortinico** [comment]
I'm closing this since I recently audited the sample app with LeakCanary and I found no leak so far. Feel free to open a new issue if the leak is still happening in AppIntro 6.0
