### ISSUE TITLE
AppIntroFragment Layout TextView -- NullPointerException

### ISSUE THREAD

**Issue by GGLabCenter** [AppIntro/AppIntro#437]
**AppIntro Version**:
Version 4.1.0

**Device/Android Version**:
Device Nexus 5X (both real and emulator)

**Issue details / Repro steps / Use case background**: 
code:
```
public class FirstLaunchActivity extends AppIntro2 {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addSlide(AppIntroFragment.newInstance("123test","testing", R.drawable.logo,
                ContextCompat.getColor(getApplicationContext(),R.color.primary)));
    }
}
```

and I obtain:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                  at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView(AppIntroBaseFragment.java:85)
                                                                  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                                                                  at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                                  at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1969)
                                                                  at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:620)
                                                                  at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                  at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                  at android.view.View.measure(View.java:19857)
                                                                  at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                  at android.view.View.measure(View.java:19857)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                  at android.view.View.measure(View.java:19857)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                  at android.view.View.measure(View.java:19857)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                  at android.view.View.measure(View.java:19857)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                  at android.view.View.measure(View.java:19857)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                  at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                  at android.view.View.measure(View.java:19857)
                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

I tried to create a new project and use the library and it's working, but I cannot understand why here it doesn't.

**Comment by GGLabCenter** [comment]
I solved (workaround) my problem by copying from the library the xml files of the AppIntroFragment and by implementing a custom fragment with the same structure.

**Comment by avluis** [comment]
@GGLabCenter Sorry for missing this -- I'll be looking into it.
Can you try the latest update and print out the crash you were getting for me once again?

**Comment by GGLabCenter** [comment]
Hi, I use now the lastest update. Here's the update (nothing changed, I still use my workaround, but i'd really like a fix for that error):

```
> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
>                                                        at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView(AppIntroBaseFragment.java:85)
>                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
>                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
>                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
>                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
>                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
>                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
>                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
>                                                        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
>                                                        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
>                                                        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
>                                                        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
>                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
>                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
>                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
>                                                        at android.view.View.measure(View.java:19857)
>                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
>                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
>                                                        at android.view.View.measure(View.java:19857)
>                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
>                                                        at android.view.View.measure(View.java:19857)
>                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                        at android.view.View.measure(View.java:19857)
>                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                        at android.view.View.measure(View.java:19857)
>                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                        at android.view.View.measure(View.java:19857)
>                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:690)
>                                                        at android.view.View.measure(View.java:19857)
>                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
>                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
>                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
>                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
>                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
>                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
>                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
>                                                        at android.view.Choreographer.doFrame(Choreographer.java:621)
>                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
>                                                        at android.os.Handler.handleCallback(Handler.java:751)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                        at android.os.Looper.loop(Looper.java:154)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:6121)
> 05-29 00:02:56.355 12265-12265/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
>                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by Anutha02** [comment]
@paolorotolo can be closed due to inactivity
