### ISSUE TITLE
Indicator color changing method not working.

### ISSUE THREAD

**Issue by zeeshansardar61** [AppIntro/AppIntro#445]
In my activity, getting error on this line.

 mController.setSelectedIndicatorColor(R.color.colorPrimary);

Error Log:

```
FATAL EXCEPTION: main
                                                                     Process: user.com.smartwashr, PID: 26838
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{user.com.smartwashr/user.com.smartwashr.activities.HowToActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.github.paolorotolo.appintro.IndicatorController.setSelectedIndicatorColor(int)' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2572)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                         at android.os.Looper.loop(Looper.java:207)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.github.paolorotolo.appintro.IndicatorController.setSelectedIndicatorColor(int)' on a null object reference
                                                                         at user.com.smartwashr.activities.HowToActivity.onCreate(HowToActivity.java:54)
                                                                         at android.app.Activity.performCreate(Activity.java:6309)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                         at android.os.Looper.loop(Looper.java:207) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5728) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
```

**Comment by paolorotolo** [comment]
You can't access mController in OnCreate since it isn't initialized.

Use this method instead:
```
setIndicatorColor(int selectedIndicatorColor, int unselectedIndicatorColor);
```

**Comment by Almaral-Engineering** [comment]
SetIndicatorColor is not working either, it does not display the colors I set

**Comment by avluis** [comment]
@Almaral-Engineering I can see part of @zeeshansardar61's code; what is yours?

**Comment by Almaral-Engineering** [comment]
in the onCreate method of my activity, after calling addSlides() method I am calling this:

`setIndicatorColor(R.color.my_blue_color, R.color.my_red_color);`

I have my_blue_color an my_red_color on the colors.xml file

**Comment by zeeshansardar61** [comment]
Thank you @paolorotolo  for answer,  @Almaral-Engineering  try this , it helped me`
setIndicatorColor(getResources.getColor(R.id.blue), getResources.getColor(R.id.red));`

**Comment by Anutha02** [comment]
@cortinico This issue can be closed now

**Comment by umang4846** [comment]
`setIndicatorColor(getResources().getColor(R.color.black),getResources().getColor(R.color.md_blue_grey_600));`

**Comment by umang4846** [comment]
`setIndicatorColor(getResources().getColor(R.color.black),getResources().getColor(R.color.md_blue_grey_600;`
