### ISSUE TITLE
Would like adjustable font sizes for title and description

### ISSUE THREAD

**Issue by fahmad2** [AppIntro/AppIntro#477]
**AppIntro Version**: 4.2.0

**Device/Android Version**: Pixel API 25

**Issue details / Repro steps / Use case background**: I am trying to customize the description (and title) text so that I can change the font size.

**Your Code**: 
 
        // Code from OnCreate Method where we use your your default slide (AppIntroFragment)

        frag1 = AppIntroFragment.newInstance("Welcome.", "fonts/bello-pro.ttf", firstText, "fonts/bello-pro.ttf", R.drawable.intro_slide1,  Color.parseColor("#5D6CBA"));
        frag2 = AppIntroFragment.newInstance("Connect With Others.", "fonts/bello-pro.ttf", secondText, "fonts/bello-pro.ttf", R.drawable.intro_slide2, Color.parseColor("#66AC5B"));
        frag3 = AppIntroFragment.newInstance("Create and Join Events.", "fonts/bello-pro.ttf", thirdText, "fonts/bello-pro.ttf", R.drawable.intro_slide3, Color.parseColor("#CC0066"));

        addSlide(frag1);
        addSlide(frag2);
        addSlide(frag3);

        //Code from Oncreate method ends here

       @Override 
       public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);

        // Do something when the slide changes.
        descText = (TextView) findViewById(R.id.description);
        descText.setTextSize(40);
    }

**Stack trace / LogCat**: NONE
```ruby
paste stack trace and/or log here
```

FIRST SCREEN
<img width="307" alt="screen shot 2017-08-24 at 12 08 11 am" src="https://user-images.githubusercontent.com/15228617/29651870-627e450a-8868-11e7-9d20-2c5bb47c20fe.png">

SWITCH TO SECOND SCREEN
<img width="306" alt="screen shot 2017-08-24 at 1 03 28 am" src="https://user-images.githubusercontent.com/15228617/29651911-abdbe4dc-8868-11e7-917e-cbdadc114561.png">

SWITCH TO THIRD SCREEN
<img width="305" alt="screen shot 2017-08-24 at 1 03 55 am" src="https://user-images.githubusercontent.com/15228617/29651918-b5c4dd00-8868-11e7-9af1-9868c2239795.png">

SWITCH BACK TO SECOND SCREEN
<img width="306" alt="screen shot 2017-08-24 at 1 04 07 am" src="https://user-images.githubusercontent.com/15228617/29651924-c11a4122-8868-11e7-9a66-2a50fc48445e.png">

SWITCH BACK TO FIRST SCREEN
<img width="305" alt="screen shot 2017-08-24 at 1 06 34 am" src="https://user-images.githubusercontent.com/15228617/29651940-d75f4946-8868-11e7-8ea4-98127a321e07.png">

NO CHANGES ARE MADE BY SWITCHING SLIDES AFTER THIS

**Comment by avluis** [comment]
Can you add the details that the issue template asks for (ignore the stack trace).

Those are needed to answer these questions:
We need to know if you are using a custom intro or a library provided intro (using the `SampleSlide` or `AppIntroFragment`).

---
Other than that, just be aware that you should be able to get a hold of an instance of your `TextViews` from code and call the appropriate methods to change their sizes at runtime.
But I'm thinking you would like this to be applied when initializing your slides rather than afterwards.

My suggestion above would allow you to define your elements per slide, so that should be a good tradeoff.

**Comment by fahmad2** [comment]
I am using AppIntroFragment. I have made changes to my initial comment above. Added some code and pictures

**Comment by avluis** [comment]
@paolorotolo
Do you think we can add this (setting font sizes to title and description) in the `SliderPage` model?
Since `SliderPage` is new enough, these changes can be used there without breaking too much of what devs already make use of.

This could be part of `4.3.0`.

**Comment by Anutha02** [comment]
@paolorotolo @cortinico. This should be fixed by #647. Font size can be set by overriding dimen values.

**Comment by Anutha02** [comment]
@cortinico please close

**Comment by gaadeveloper** [comment]
Hello @Anutha02 I'm using AppIntro:5.1.0 and can't override the dimen values. This is what I've done in my dimens.xml to try to change it:

<dimen name="appintro_desctext_size" tools:override="true">10sp</dimen>
    <dimen name="appintro_desc_padding" tools:override="true">10dp</dimen>
    <dimen name="appintro_head_padding" tools:override="true">10dp</dimen>
    <dimen name="appintro_headtext_size" tools:override="true">10sp</dimen>

But it has no effect whatsoever.

Could you please write the code here to see how I should implement it?

I'm using addSlide and AppIntroFragment.newInstance to create the slides.

**Comment by Anutha02** [comment]
@gaadeveloper try using 6.0.0 alpha01

**Comment by gaadeveloper** [comment]
Using any of these crashes the app:

`implementation 'com.github.AppIntro:AppIntro:6.0.0-alpha01'`
`implementation 'com.github.AppIntro:AppIntro:6.0.0 alpha01'`

**Comment by Anutha02** [comment]
@gaadeveloper Can you please post the stack trace, so that we can fix the issue before the satbel release.

**Comment by gaadeveloper** [comment]
@Anutha02 This is what I get in Build:
```
ERROR: Failed to resolve: com.github.AppIntro:AppIntro:6.0.0-alpha01
Show in Project Structure dialog
Affected Modules: app
```

**Comment by Anutha02** [comment]
It's alpha1 not alpha01

**Comment by gaadeveloper** [comment]
Ok that solved the issue with the integration of the library but I keep getting a crash. First I had to change the order of the newInstance parameters because it gave me a crash. Now that that is not a problem when I run it I get this:

`2019-03-23 12:21:36.824 26685-26685/com.example.silentlibrary E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.silentlibrary, PID: 26685
    android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:236)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:891)
        at android.content.res.Resources.getDrawable(Resources.java:834)
        at android.content.Context.getDrawable(Context.java:605)
        at android.view.View.setBackgroundResource(View.java:21712)
        at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView(AppIntroBaseFragment.kt:118)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2539)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1227)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:710)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2063)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1808)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1685)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:560)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:148)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:23407)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1676)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:909)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2952)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2236)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1843)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7978)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
2019-03-23 12:21:36.824 26685-26690/com.example.silentlibrary I/zygote: After code cache collection, code=123KB, data=86KB
2019-03-23 12:21:36.824 26685-26690/com.example.silentlibrary I/zygote: Increasing code cache capacity to 512KB
2019-03-23 12:21:36.825 26685-26685/com.example.silentlibrary E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`


This is my code:

`public class IntroActivity extends AppIntro {

    Context mContext = this;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);


        @FontRes int luckiestguyfont = R.font.luckiestguy;
        @FontRes int karlafont = R.font.karla;



        addSlide(AppIntroFragment.newInstance(getString(R.string.how_to_play_one), getString(R.string.how_to_play_one_description), karlafont, karlafont, R.drawable.group_challenge, Color.parseColor("#247BA0"), getResources().getColor(android.R.color.white), getResources().getColor(android.R.color.white)));
        addSlide(AppIntroFragment.newInstance(getString(R.string.how_to_play_two), getString(R.string.how_to_play_two_description), karlafont, karlafont, R.drawable.challenges_icon, Color.parseColor("#70C1B3"), getResources().getColor(android.R.color.white), getResources().getColor(android.R.color.white)));
        addSlide(AppIntroFragment.newInstance(getString(R.string.how_to_play_three), getString(R.string.how_to_play_three_description),karlafont, karlafont, R.drawable.players_choose_card, Color.parseColor("#A2AA7E"), getResources().getColor(android.R.color.white), getResources().getColor(android.R.color.white)));
        addSlide(AppIntroFragment.newInstance(getString(R.string.how_to_play_four), getString(R.string.how_to_play_four_description), karlafont, karlafont, R.drawable.silence, Color.parseColor("#6D6875"), getResources().getColor(android.R.color.white), getResources().getColor(android.R.color.white)));


        showSkipButton(true);
        setProgressButtonEnabled(true);
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);

        Intent intent = new Intent(IntroActivity.this, Home.class);
        startActivity(intent);
        overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left);
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);

        Intent intent = new Intent(IntroActivity.this, Home.class);
        startActivity(intent);
        overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left);
    }





    @Override
    public void finish() {

        if (isTaskRoot()){
            super.finish();
        }

        else
        {
            super.finish();
            overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_left);
        }



    }
}`

**Comment by Anutha02** [comment]
@gaadeveloper I will take a look at it ASAP and try to help you soon.

**Comment by Anutha02** [comment]
@gaadeveloper in the meantime I would advise you to try using the Slider page model. Take a look here: 
https://github.com/AppIntro/AppIntro/blob/master/example/src/main/java/com/amqtech/opensource/appintroexample/ui/mainTabs/intro/DefaultIntro2.java

**Comment by gaadeveloper** [comment]
Thank you @Anutha02 

I replaced this part of my code:

`addSlide(AppIntroFragment.newInstance(getString(R.string.how_to_play_one), getString(R.string.how_to_play_one_description), karlafont, karlafont, R.drawable.group_challenge, Color.parseColor("#247BA0"), getResources().getColor(android.R.color.white), getResources().getColor(android.R.color.white)));
        addSlide(AppIntroFragment.newInstance(getString(R.string.how_to_play_two), getString(R.string.how_to_play_two_description), karlafont, karlafont, R.drawable.challenges_icon, Color.parseColor("#70C1B3"), getResources().getColor(android.R.color.white), getResources().getColor(android.R.color.white)));
        addSlide(AppIntroFragment.newInstance(getString(R.string.how_to_play_three), getString(R.string.how_to_play_three_description),karlafont, karlafont, R.drawable.players_choose_card, Color.parseColor("#A2AA7E"), getResources().getColor(android.R.color.white), getResources().getColor(android.R.color.white)));
        addSlide(AppIntroFragment.newInstance(getString(R.string.how_to_play_four), getString(R.string.how_to_play_four_description), karlafont, karlafont, R.drawable.silence, Color.parseColor("#6D6875"), getResources().getColor(android.R.color.white), getResources().getColor(android.R.color.white)));
`

To this:
` SliderPage sliderPage1 = new SliderPage();
        sliderPage1.setTitle(getString(R.string.how_to_play_one));
        sliderPage1.setDescription(getString(R.string.how_to_play_one_description));
        sliderPage1.setTitleTypefaceFontRes(R.font.karla);
        sliderPage1.setDescTypefaceFontRes(R.font.karla);
        sliderPage1.setImageDrawable(R.drawable.group_challenge);
        sliderPage1.setBgDrawable(Color.parseColor("#247BA0"));
        addSlide(AppIntroFragment.newInstance(sliderPage1));

        SliderPage sliderPage2 = new SliderPage();
        sliderPage2.setTitle(getString(R.string.how_to_play_two));
        sliderPage2.setDescription(getString(R.string.how_to_play_two_description));
        sliderPage2.setTitleTypefaceFontRes(R.font.karla);
        sliderPage2.setDescTypefaceFontRes(R.font.karla);
        sliderPage2.setImageDrawable(R.drawable.challenges_icon);
        sliderPage2.setBgDrawable(Color.parseColor("#70C1B3"));
        addSlide(AppIntroFragment.newInstance(sliderPage2));

        SliderPage sliderPage3 = new SliderPage();
        sliderPage3.setTitle(getString(R.string.how_to_play_three));
        sliderPage3.setDescription(getString(R.string.how_to_play_three_description));
        sliderPage3.setTitleTypefaceFontRes(R.font.karla);
        sliderPage3.setDescTypefaceFontRes(R.font.karla);
        sliderPage3.setImageDrawable(R.drawable.players_choose_card);
        sliderPage3.setBgDrawable(Color.parseColor("#A2AA7E"));
        addSlide(AppIntroFragment.newInstance(sliderPage3));

        SliderPage sliderPage4 = new SliderPage();
        sliderPage4.setTitle(getString(R.string.how_to_play_four));
        sliderPage4.setDescription(getString(R.string.how_to_play_four_description));
        sliderPage4.setTitleTypefaceFontRes(R.font.karla);
        sliderPage4.setDescTypefaceFontRes(R.font.karla);
        sliderPage4.setImageDrawable(R.drawable.silence);
        sliderPage4.setBgDrawable(Color.parseColor("#6D6875"));
        addSlide(AppIntroFragment.newInstance(sliderPage4));
`

But keep getting the same error:

`   --------- beginning of crash
2019-03-23 12:53:22.010 28512-28512/com.example.silentlibrary E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.silentlibrary, PID: 28512
    android.content.res.Resources$NotFoundException: Resource ID #0xff247ba0
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:236)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:891)
        at android.content.res.Resources.getDrawable(Resources.java:834)
        at android.content.Context.getDrawable(Context.java:605)
        at android.view.View.setBackgroundResource(View.java:21712)
        at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView(AppIntroBaseFragment.kt:118)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2539)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1227)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:710)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2063)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1808)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1685)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:560)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:148)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:23407)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1676)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6967)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:909)
        at android.view.View.measure(View.java:23407)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2952)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2236)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1843)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7978)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
2019-03-23 12:53:22.010 28512-28512/com.example.silentlibrary E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

**Comment by Anutha02** [comment]
@gaadeveloper You have to use setBgColor if you pass a colour to the method

**Comment by Anutha02** [comment]
@gaadeveloper BTW What API level are you using?

**Comment by gaadeveloper** [comment]
Thank you @Anutha02 , it didn't crash now and it changed the size of the title and description.

I use compileSdkVersion 28, minSdkVersion 15.

One last question: I migrated to AndroidX because I assume that the change in size of the title and description in this library is only possible with the AndroidX implementation of it. Is this true or can we change the size of them with the support compatible implementation?

I'm afraid things may go wrong with AndroidX and have to move back to my backed-up support project.

**Comment by Anutha02** [comment]
@gaadeveloper, I am new here , so I don't know😅. Let me just check it.

**Comment by Anutha02** [comment]
@gaadeveloper, Sorry, it appears that the font sizes were hard-coded in earlier versions.

**Comment by gaadeveloper** [comment]
@Anutha02 Thank you!!!

**Comment by Anutha02** [comment]
You can try the approach used in the question, but it obviously didn't work for v4.2.0, you might wanna give it a try on v4.2.3

**Comment by gaadeveloper** [comment]
@Anutha02 I'll stick with AndroidX if I can. What I have observed is that the only thing that is not configurable is the size of the 'Skip' text at the bottom bar. It would be nice to adjust its size too but if not I can live without it.

**Comment by Anutha02** [comment]
@gaadeveloper Actually it is coming. Take a look at #660. You can override the appintroskipbuttonstyle after it gets merged

**Comment by gaadeveloper** [comment]
@Anutha02 That will be nice. Is there a way I can receive notifications of AppIntro updates?

**Comment by Anutha02** [comment]
@gaadeveloper. Not any way that I know of. Just keep an eye on the releases section 😊
