### ISSUE TITLE
Permission slides doesn't show up

### ISSUE THREAD

**Issue by aidinism** [AppIntro/AppIntro#508]
i try to ask for permissions on (Galaxy S6 / Android 7.0), but no luck

other slides are visible but no dialog or anything to ask for permission. 

ps: ( slides are not enable to touch [as expected]  but back/next button works )

so i just stuck on fist slide without any permission alert.

code : 
```
for (int i = 1; i < 6; i++) {
            Bundle bundle = new Bundle();
            bundle.putInt("code", i);
            FragmentIntro fragmentIntro = new FragmentIntro();
            fragmentIntro.setArguments(bundle);
            addSlide(fragmentIntro);
        }

        askForPermissions(new String[]{Manifest.permission.CAMERA}, 1);


        setBarColor(Color.parseColor("#99000000"));
```

**Comment by Aidin** [comment]
Additional log:

   ```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView(AppIntroBaseFragment.java:85)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2034)
at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
at android.view.Choreographer.doCallbacks(Choreographer.java:603)
at android.view.Choreographer.doFrame(Choreographer.java:571)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5643)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

**Comment by hamsoft-uganda** [comment]
Hello did you get any solution for permission dialog not showing up??

**Comment by SharmadDesai** [comment]
Any Updates?

**Comment by voghDev** [comment]
Same here. No permissions appear. Probably we are missing something

**Comment by Anutha02** [comment]
I guess you haven't declared the permissions in your manifest file. If this is the case, then the permissions don't appear.

**Comment by Anutha02** [comment]
@cortinico Solved

**Comment by Anutha02** [comment]
@paolorotolo can be closed, as the most probable cause is not declaring the permissions in the manifest( Even I was stuck because of this for a while)
