### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by duetdroid2018** [AppIntro/AppIntro#517]
**AppIntro Version**:
AppIntro 4.2.2

**Device/Android Version**:
Android emulator/ android-16

**Issue details / Repro steps / Use case background**: 
I am running the latest appIntro in Android-16 emulator. I meet a crash "NoSuchMethodError".

**Your Code**: 
I am using your demo app.

**Stack trace / LogCat**:
```ruby
E/AndroidRuntime( 2366): FATAL EXCEPTION: main
E/AndroidRuntime( 2366): java.lang.NoSuchMethodError: android.content.res.Configuration.getLayoutDirection
E/AndroidRuntime( 2366):        at com.github.paolorotolo.appintro.util.LayoutUtil.isRtl(LayoutUtil.java:10)
E/AndroidRuntime( 2366):        at com.github.paolorotolo.appintro.AppIntroBase.isRtl(AppIntroBase.java:760)
E/AndroidRuntime( 2366):        at com.github.paolorotolo.appintro.AppIntroBase.preinit(AppIntroBase.java:102)
E/AndroidRuntime( 2366):        at com.github.paolorotolo.appintro.AppIntroBase.onCreate(AppIntroBase.java:83)
E/AndroidRuntime( 2366):        at com.amqtech.opensource.appintroexample.ui.mainTabs.intro.DefaultIntro.onCreate(DefaultIntro.java:23)
E/AndroidRuntime( 2366):        at android.app.Activity.performCreate(Activity.java:5008)
E/AndroidRuntime( 2366):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
E/AndroidRuntime( 2366):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
E/AndroidRuntime( 2366):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
E/AndroidRuntime( 2366):        at android.app.ActivityThread.access$600(ActivityThread.java:130)
E/AndroidRuntime( 2366):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
E/AndroidRuntime( 2366):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2366):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2366):        at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 2366):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2366):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2366):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 2366):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 2366):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 1361):   Force finishing activity com.amqtech.opensource.appintroexample/.ui.mainTabs.intro.DefaultIntro
W/ActivityManager( 1361):   Force finishing activity com.amqtech.opensource.appintroexample/.ui.MainActivity
```

**Comment by Anutha02** [comment]
@cortinico @paolorotolo The method isRTL() should be of this form:
` fun isRtl(ctx: Context): Boolean {
       var isRTL : Boolean
        isRTL = false //RTL is supported only on API 17, so it will be false on API<17
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            isRTL = ctx.resources.configuration.layoutDirection == View.LAYOUT_DIRECTION_RTL
        }
        return isRTL
    }`

**Comment by Anutha02** [comment]
@cortinico I have tested the app on API 16. It does not crash anymore. This issue should be closed.
