### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by amos-yau** [AppIntro/AppIntro#638]
**AppIntro Version**: 4.2.3

**Device/Android Version**: 5,6,7,8

**Issue details / Repro steps / Use case background**: from Crashlytic collected, happened 40-50 times.

**Your Code**: 
            SliderPage slideNoNeedNetwork = new SliderPage();
            slideNoNeedNetwork.setTitle(getString(R.string.no_need_network_title));
            slideNoNeedNetwork.setTitleColor(Color.DKGRAY);
            slideNoNeedNetwork.setDescription(getString(R.string.no_need_network_message));
            slideNoNeedNetwork.setDescColor(Color.DKGRAY);
            slideNoNeedNetwork.setImageDrawable(R.drawable.no_need_network);
            slideNoNeedNetwork.setBgColor(Color.rgb(220, 220, 50));
            addSlide(AppIntroFragment.newInstance(slideNoNeedNetwork));

- the above repeated 7 times for different contents

**Stack trace / LogCat**:
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x7f07090e
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
       at android.content.res.Resources.getValue(Resources.java:1316)
       at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(Unknown Source:18)
       at android.support.v7.widget.AppCompatDrawableManager.get(Unknown Source:10)
       at android.support.v7.widget.AppCompatDrawableManager.get(Unknown Source:2)
       at android.support.v7.content.res.AppCompatResources.getDrawable(Unknown Source:4)
       at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(Unknown Source:8)
       at android.support.v7.widget.AppCompatImageView.setImageResource(Unknown Source:6)
       at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView(Unknown Source:131)
       at android.support.v4.app.Fragment.performCreateView(Unknown Source:22)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source:590)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:38)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source:46)
       at android.support.v4.app.BackStackRecord.executeOps(Unknown Source:169)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source:38)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source:116)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source:88)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source:31)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(Unknown Source:6)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(Unknown Source:6)
       at android.support.v4.view.ViewPager.populate(Unknown Source:390)
       at android.support.v4.view.ViewPager.populate(Unknown Source:2)
       at android.support.v4.view.ViewPager.onMeasure(Unknown Source:212)
       at android.view.View.measure(View.java:22071)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source:172)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2422)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1504)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by cortinico** [comment]
Hey @amos-yau 

Looks like you're passing the wrong resource to the `slideNoNeedNetwork.setImageDrawable(...)` calls. Please make sure the drawables you pass are actually available in the final APK.

Closing as this doesn't look related to AppIntro.

**Comment by amos-yau** [comment]
@cortinico thanks for your reply.

I've downloaded the device-specific (crashed device) APK from Play Console's Artifact Library, and then used Android Studio to look into the APK, all the images are there, in a separated APK named "config.xxhdpi.apk", apart from the "base.apk".

I wonder is the problem due to AppBundle is being used?

**Comment by cortinico** [comment]
Awesome :) Thanks for the follow up
