### ISSUE TITLE
How to change the title position

### ISSUE THREAD

**Issue by Asendo316** [AppIntro/AppIntro#652]
I'm using AppIntro:v4.2.3, I want to place the title text below the Image and directly above the description.
How do i do this please

**Comment by Anutha02** [comment]
One way is to use custom fragments.

**Comment by Asendo316** [comment]
I already tried using a custom fragment but when i swipe to switch to a second fragment i get this error

java.lang.IllegalStateException: Can't change tag of fragment RateFragment{38915ae #0 id=0x7f0a01a6 android:switcher:2131362214:0}: was android:switcher:2131362214:0 now android:switcher:2131362214:2
        at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:409)
        at android.support.v4.app.BackStackRecord.add(BackStackRecord.java:391)
        at android.support.v4.app.FragmentPagerAdapter.instantiateItem(FragmentPagerAdapter.java:107)
        at com.github.paolorotolo.appintro.PagerAdapter.instantiateItem(PagerAdapter.java:56)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1224)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Anutha02** [comment]
Hmmmm... Can you give your code and layout of fragments?

**Comment by Asendo316** [comment]
This is the fragment class
`public class RateFragment extends Fragment {


    public RateFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_rate, container, false);
    }

}`

This is the fragment xml

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".fragment.intro.RateFragment">

    
    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="@string/hello_blank_fragment" />

</FrameLayout>`

**Comment by Anutha02** [comment]
Try setting the ID of fragment as main for first fragment, main2 for second and tell me what happens

**Comment by Anutha02** [comment]
Also please show me your activity code where you are initialising the fragment.

**Comment by Anutha02** [comment]
Also, try this

https://github.com/AppIntro/AppIntro/blob/master/README.md#custom-slides-example

**Comment by Asendo316** [comment]
Okay i think i got it working now. I was using a fragment twice in the   addSlide(fragment);
thanks

**Comment by Anutha02** [comment]
Great
