### ISSUE TITLE
com.github.paolorotolo.appintro.AppIntroBase.onCreate 

### ISSUE THREAD

**Issue by alkincakiralar1996** [AppIntro/AppIntro#907]
**AppIntro Version**: 4.0.0
implementation 'com.github.paolorotolo:appintro:4.0.0'

**Device/Android Version**: 
<img width="406" alt="Screen Shot 2020-12-09 at 10 01 01" src="https://user-images.githubusercontent.com/29644075/101596047-74937380-3a05-11eb-98e7-e6591e1e75ba.png">
<img width="426" alt="Screen Shot 2020-12-09 at 10 01 18" src="https://user-images.githubusercontent.com/29644075/101596066-7cebae80-3a05-11eb-8551-f8c75b0e2dcc.png">
<img width="418" alt="Screen Shot 2020-12-09 at 10 00 43" src="https://user-images.githubusercontent.com/29644075/101596019-68a7b180-3a05-11eb-84c1-701d705db645.png">

**Issue details / Repro steps / Use case background**: This library works only when user start the application first time and sometimes i get crash on firebase, i tried a lot of things and nothing get crashed

the error is : 
com.github.paolorotolo.appintro.AppIntroBase.onCreate (AppIntroBase.java:80)

my code : 

**when open the project it starts with below activity code** 

```
public class ActivitySplash extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        UtilPreferences utilPreferences = new UtilPreferences(this);

        if (!utilPreferences.getIsIntroActivated()) {
            startActivity(new Intent(getApplicationContext(), ActivityIntro.class)); **// detect here**
        }
        if (utilPreferences.getIsIntroActivated() && !utilPreferences.getIsLoggedIn()) {
            startActivity(new Intent(getApplicationContext(), ActivityLogin.class));
        }
        if (utilPreferences.getIsIntroActivated() && utilPreferences.getIsLoggedIn()) {

            if (getIntent().getStringExtra("route_name") != null) {

                String routeId = null;

                if (getIntent().getStringExtra("route_id") != null) {

                    routeId = getIntent().getStringExtra("route_id");

                }

                Intent intent = new Intent(getApplicationContext(), ActivityMain.class);
                intent.putExtra("route_name", getIntent().getStringExtra("route_name"));
                intent.putExtra("route_id", routeId);

                startActivity(intent);

            } else {

                Intent intent = new Intent(getApplicationContext(), ActivityMain.class);
                startActivity(intent);
            }

        }

    }

}
```

```
public class ActivityIntro extends AppIntro {

    UtilPreferences utilPreferences;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        utilPreferences = new UtilPreferences(this);

        Window window = this.getWindow();

        window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);

        window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);

        window.setStatusBarColor(ContextCompat.getColor(this, R.color.m80));

        showSkipButton(false);
        setColorSkipButton(ContextCompat.getColor(this, R.color.white));
        setColorDoneText(ContextCompat.getColor(this, R.color.white));
        setIndicatorColor(Color.parseColor("#FFFFFF"), Color.parseColor("#FFFFFF"));
        setNextArrowColor(Color.parseColor("#303030"));
        setSeparatorColor(ContextCompat.getColor(this, R.color.m80));
        setBarColor(ContextCompat.getColor(this, R.color.m80));

        setProgressButtonEnabled(true);

        setDoneText(LanguageHelper.get(this, R.string.intro_continue).toUpperCase());

        addSlide(new FragmentWelcome());

        addSlide(new FragmentIntro(
                R.drawable.intro_1_back, R.drawable.intro_1_image, R.drawable.unicon_search_icon_alt, R.string.intro_page_1_title, R.string.intro_page_1_message));

        addSlide(new FragmentIntro(
                R.drawable.intro_back_2, R.drawable.intro_2_image, R.drawable.unicon_bell_icon_alt, R.string.intro_page_2_title, R.string.intro_page_2_message));

        addSlide(new FragmentIntro(
                R.drawable.intro_3_back, R.drawable.intro_3_image, R.drawable.unicon_bolt_icon_alt, R.string.intro_page_3_title, R.string.intro_page_3_message));

        addSlide(new FragmentIntro(
                R.drawable.intro_4_back, R.drawable.intro_4_image, R.drawable.unicon_money_icon, R.string.intro_page_4_title, null));

    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        utilPreferences.setIsIntroActived(true);
        startActivity(utilPreferences.getIsLoggedIn() ? new Intent(this, ActivityMain.class) : new Intent(this, ActivityLogin.class));
    }

    @Override
    public void onBackPressed() {
        //super.onBackPressed();
    }
}

```

**Fragment Welcome** 

**public class FragmentWelcome extends Fragment {

    @BindView(R.id.pt_btn)
    Button portuguese_btn;
    @BindView(R.id.eng_btn)
    Button english_btn;
    @BindView(R.id.tr_btn)
    Button turkish_btn;

    public FragmentWelcome() {

    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        super.onCreateView(inflater, container, savedInstanceState);

        View view = inflater.inflate(R.layout.layout_welcome, container, false);

        ButterKnife.bind(this, view);

        english_btn.setOnClickListener(view1 -> {

            this.setLanguage("en");//en_US

        });

        turkish_btn.setOnClickListener(view1 -> {

            this.setLanguage("tr");//tr_TR

        });

        portuguese_btn.setOnClickListener(view1 -> {

            this.setLanguage("pt");//pt_PT

        });

        return view;

    }

    private void setLanguage(String language) {
        ApplicationClass.setUpLanguage(getContext(), language);
        UtilPreferences utilPreferences = new UtilPreferences(getContext());
        utilPreferences.setAppLanguage(language);
        Intent refresh = new Intent(getActivity(), getActivity().getClass());
        startActivity(refresh);
        getActivity().finish();

    }
}**

Fragment Intro

```
public class FragmentIntro extends Fragment {

    @BindView(R.id.container_view)
    RelativeLayout containerView;

    @BindView(R.id.hero_image)
    ImageView heroImage;
    @BindView(R.id.intro_icon)
    ImageView iconImage;
    @BindView(R.id.title_message)
    TextView titleMessage;
    @BindView(R.id.description_message)
    TextView titleDescription;


    private int layoutBackground;

    private int heroImageSrc;
    private int iconImageSrc;

    private Integer titleText;
    private Integer descriptionText;

    public FragmentIntro() {
        // Required empty public constructor
    }

    @SuppressLint("ValidFragment")
    public FragmentIntro(int layoutBackground, int heroImage, int icon, Integer title, Integer desc) {

        this.layoutBackground = layoutBackground;
        this.heroImageSrc = heroImage;
        this.iconImageSrc = icon;
        this.titleText = title;
        this.descriptionText = desc;

    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.layout_intro, container, false);

        ButterKnife.bind(this, view);

        containerView.setBackground(getResources().getDrawable(layoutBackground));
        heroImage.setImageDrawable(getResources().getDrawable(heroImageSrc));
        iconImage.setImageDrawable(getResources().getDrawable(iconImageSrc));

        if (titleText != null) {

            titleMessage.setText(titleText);

        }

        if (descriptionText != null) {

            titleDescription.setText(descriptionText);

        }

        return view;
    }
}

```

the error message : 
```
Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080141
       at android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:387)
       at android.content.res.ResourcesImplEx.getResourcePackageName(ResourcesImplEx.java:50)
       at android.content.res.HwResourcesImpl.getThemePackageName(HwResourcesImpl.java:1742)
       at android.content.res.HwResourcesImpl.loadDrawable(HwResourcesImpl.java:1340)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:885)
       at android.content.res.Resources.loadDrawable(Resources.java:1004)
       at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1207)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:1182)
       at android.widget.ImageView.<init>(ImageView.java:213)
       at android.widget.ImageButton.<init>(ImageButton.java:86)
       at android.widget.ImageButton.<init>(ImageButton.java:82)
       at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:73)
       at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:69)
       at androidx.appcompat.app.AppCompatViewInflater.createImageButton(AppCompatViewInflater.java:207)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:123)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
       at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1071)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1007)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
       at com.github.paolorotolo.appintro.AppIntroBase.onCreate(AppIntroBase.java:80)
       at com.myproject.activities.intro.ActivityIntro.onCreate(ActivityIntro.java:27)
       at android.app.Activity.performCreate(Activity.java:8085)
       at android.app.Activity.performCreate(Activity.java:8073)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8349)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by cortinico** [comment]
> Unable to find resource ID #0x7f080141

Are you able to open your `R.java` and let us know which resource is the one that is missing? That will help us debug if the resource missing is coming from the library or not.

**Comment by alkincakiralar1996** [comment]
Are you use ImageButton widget in your library ?

**Comment by alkincakiralar1996** [comment]
i upgraded library version to 6.0 i will report when crash takes again

**Comment by cortinico** [comment]
> i upgraded library version to 6.0 i will report when crash takes again

Oh, I haven't noticed you were actually on a older version (4.0.0).
I'm closing for now. Feel free to reopen if the issue arise again on 6.x
