### ISSUE TITLE
Strict mode usages 

### ISSUE THREAD

**Issue by KaanRF** [AppIntro/AppIntro#914]
Hello, 

I have observed below strict mode usage with AppIntro 6.x version. My activity is the same as #913 

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at h.b.c.n.M(SourceFile:44)
	at h.b.c.n.v(SourceFile:1)
	at h.b.c.k.setContentView(SourceFile:1)
	at com.github.appintro.AppIntroBase.onCreate(SourceFile:7)
	at com.github.appintro.AppIntro2.onCreate(SourceFile:1)
	at com.kaankandemirsoftware.iocome.view.ui.startsequence.introduction.IntroductionActivity.onCreate(SourceFile:1)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/graphics/FontFamily;-><init>()V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredConstructorInternal(Native Method)
	at java.lang.Class.getConstructor0(Class.java:2325)
	at java.lang.Class.getConstructor(Class.java:1725)
	at h.h.d.g.<init>(SourceFile:3)
	at h.h.d.h.<init>(SourceFile:1)
	at h.h.d.d.<clinit>(SourceFile:3)
	at androidx.appcompat.widget.AppCompatTextView.setTypeface(SourceFile:2)
	at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2037)
	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2008)
	at android.widget.TextView.applyTextAppearance(TextView.java:3640)
	at android.widget.TextView.<init>(TextView.java:1498)
	at android.widget.TextView.<init>(TextView.java:869)
	at androidx.appcompat.widget.AppCompatTextView.<init>(SourceFile:2)
	at com.google.android.material.textview.MaterialTextView.<init>(SourceFile:1)
	at com.google.android.material.theme.MaterialComponentsViewInflater.e(SourceFile:1)
	at h.b.c.n.onCreateView(SourceFile:42)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.github.appintro.AppIntroBaseFragment.onCreateView(SourceFile:1)
	at androidx.fragment.app.Fragment.performCreateView(SourceFile:4)
	at h.l.b.p.V(SourceFile:86)
	at h.l.b.p.T(SourceFile:4)
	at h.l.b.a.n(SourceFile:26)
	at h.l.b.p.E(SourceFile:51)
	at h.l.b.p.c0(SourceFile:10)
	at h.l.b.p.D(SourceFile:5)
	at h.l.b.a.f(SourceFile:3)
	at h.l.b.u.finishUpdate(SourceFile:4)
	at h.z.a.b.populate(SourceFile:51)
	at h.z.a.b.populate(SourceFile:1)
	at h.z.a.b.onMeasure(SourceFile:25)
	at android.view.View.measure(View.java:23169)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(SourceFile:77)
	at h.f.b.h.e.X(SourceFile:50)
	at h.f.b.h.l.h.g(SourceFile:3)
	at h.f.b.h.l.h.f(SourceFile:15)
	at h.f.b.h.l.h.g(SourceFile:28)
	at h.f.b.h.e.P(SourceFile:83)
	at h.f.b.h.l.b.b(SourceFile:13)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:224)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:21)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewRootImpl.performMeasure(ViewRoo
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/graphics/FontFamily;->abortCreation()V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at h.h.d.g.<init>(SourceFile:7)
	at h.h.d.h.<init>(SourceFile:1)
	at h.h.d.d.<clinit>(SourceFile:3)
	at androidx.appcompat.widget.AppCompatTextView.setTypeface(SourceFile:2)
	at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2037)
	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2008)
	at android.widget.TextView.applyTextAppearance(TextView.java:3640)
	at android.widget.TextView.<init>(TextView.java:1498)
	at android.widget.TextView.<init>(TextView.java:869)
	at androidx.appcompat.widget.AppCompatTextView.<init>(SourceFile:2)
	at com.google.android.material.textview.MaterialTextView.<init>(SourceFile:1)
	at com.google.android.material.theme.MaterialComponentsViewInflater.e(SourceFile:1)
	at h.b.c.n.onCreateView(SourceFile:42)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.github.appintro.AppIntroBaseFragment.onCreateView(SourceFile:1)
	at androidx.fragment.app.Fragment.performCreateView(SourceFile:4)
at androidx.fragment.app.Fragment.performCreateView(SourceFile:4)
	at h.l.b.p.V(SourceFile:86)
	at h.l.b.p.T(SourceFile:4)
	at h.l.b.a.n(SourceFile:26)
	at h.l.b.p.E(SourceFile:51)
	at h.l.b.p.c0(SourceFile:10)
	at h.l.b.p.D(SourceFile:5)
	at h.l.b.a.f(SourceFile:3)
	at h.l.b.u.finishUpdate(SourceFile:4)
	at h.z.a.b.populate(SourceFile:51)
	at h.z.a.b.populate(SourceFile:1)
	at h.z.a.b.onMeasure(SourceFile:25)
	at android.view.View.measure(View.java:23169)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(SourceFile:77)
	at h.f.b.h.e.X(SourceFile:50)
	at h.f.b.h.l.h.g(SourceFile:3)
	at h.f.b.h.l.h.f(SourceFile:15)
	at h.f.b.h.l.h.g(SourceFile:28)
	at h.f.b.h.e.P(SourceFile:83)
	at h.f.b.h.l.b.b(SourceFile:13)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:224)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:21)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
	at android.view.View.measure(View.java:23169)
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at h.h.d.g.n(SourceFile:1)
	at h.h.d.g.<init>(SourceFile:4)
	at h.h.d.h.<init>(SourceFile:1)
	at h.h.d.d.<clinit>(SourceFile:3)
	at androidx.appcompat.widget.AppCompatTextView.setTypeface(SourceFile:2)
	at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2037)
	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2008)
	at android.widget.TextView.applyTextAppearance(TextView.java:3640)
	at android.widget.TextView.<init>(TextView.java:1498)
	at android.widget.TextView.<init>(TextView.java:869)
	at androidx.appcompat.widget.AppCompatTextView.<init>(SourceFile:2)
	at com.google.android.material.textview.MaterialTextView.<init>(SourceFile:1)
	at com.google.android.material.theme.MaterialComponentsViewInflater.e(SourceFile:1)
	at h.b.c.n.onCreateView(SourceFile:42)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.github.appintro.AppIntroBaseFragment.onCreateView(SourceFile:1)
	at androidx.fragment.app.Fragment.performCreateView(SourceFile:4)
	at h.l.b.p.V(SourceFile:86)
	at h.l.b.p.T(SourceFile:4)
	at h.l.b.a.n(SourceFile:26)
	at h.l.b.p.E(SourceFile:51)
	at h.l.b.p.c0(SourceFile:10)
	at h.l.b.p.D(SourceFile:5)
	at h.l.b.a.f(SourceFile:3)
	at h.l.b.u.finishUpdate(SourceFile:4)
	at h.z.a.b.populate(SourceFile:51)
	at h.z.a.b.populate(SourceFile:1)
	at h.z.a.b.onMeasure(SourceFile:25)
	at android.view.View.measure(View.java:23169)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(SourceFile:77)
	at h.f.b.h.e.X(SourceFile:50)
	at h.f.b.h.l.h.g(SourceFile:3)
	at h.f.b.h.l.h.f(SourceFile:15)
	at h.f.b.h.l.h.g(SourceFile:28)
	at h.f.b.h.e.P(SourceFile:83)
	at h.f.b.h.l.b.b(SourceFile:13)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:224)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:21)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(Fr
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at h.h.d.g.o(SourceFile:1)
	at h.h.d.g.<init>(SourceFile:5)
	at h.h.d.h.<init>(SourceFile:1)
	at h.h.d.d.<clinit>(SourceFile:3)
	at androidx.appcompat.widget.AppCompatTextView.setTypeface(SourceFile:2)
	at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2037)
	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2008)
	at android.widget.TextView.applyTextAppearance(TextView.java:3640)
	at android.widget.TextView.<init>(TextView.java:1498)
	at android.widget.TextView.<init>(TextView.java:869)
	at androidx.appcompat.widget.AppCompatTextView.<init>(SourceFile:2)
	at com.google.android.material.textview.MaterialTextView.<init>(SourceFile:1)
	at com.google.android.material.theme.MaterialComponentsViewInflater.e(SourceFile:1)
	at h.b.c.n.onCreateView(SourceFile:42)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.github.appintro.AppIntroBaseFragment.onCreateView(SourceFile:1)
	at androidx.fragment.app.Fragment.performCreateView(SourceFile:4)
	at h.l.b.p.V(SourceFile:86)
	at h.l.b.p.T(SourceFile:4)
	at h.l.b.a.n(SourceFile:26)
	at h.l.b.p.E(SourceFile:51)
	at h.l.b.p.c0(SourceFile:10)
	at h.l.b.p.D(SourceFile:5)
	at h.l.b.a.f(SourceFile:3)
	at h.l.b.u.finishUpdate(SourceFile:4)
	at h.z.a.b.populate(SourceFile:51)
	at h.z.a.b.populate(SourceFile:1)
	at h.z.a.b.onMeasure(SourceFile:25)
	at android.view.View.measure(View.java:23169)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(SourceFile:77)
	at h.f.b.h.e.X(SourceFile:50)
	at h.f.b.h.l.h.g(SourceFile:3)
	at h.f.b.h.l.h.f(SourceFile:15)
	at h.f.b.h.l.h.g(SourceFile:28)
	at h.f.b.h.e.P(SourceFile:83)
	at h.f.b.h.l.b.b(SourceFile:13)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:224)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:21)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.int
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/graphics/FontFamily;->freeze()Z
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at h.h.d.g.<init>(SourceFile:6)
	at h.h.d.h.<init>(SourceFile:1)
	at h.h.d.d.<clinit>(SourceFile:3)
	at androidx.appcompat.widget.AppCompatTextView.setTypeface(SourceFile:2)
	at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2037)
	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2008)
	at android.widget.TextView.applyTextAppearance(TextView.java:3640)
	at android.widget.TextView.<init>(TextView.java:1498)
	at android.widget.TextView.<init>(TextView.java:869)
	at androidx.appcompat.widget.AppCompatTextView.<init>(SourceFile:2)
	at com.google.android.material.textview.MaterialTextView.<init>(SourceFile:1)
	at com.google.android.material.theme.MaterialComponentsViewInflater.e(SourceFile:1)
	at h.b.c.n.onCreateView(SourceFile:42)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.github.appintro.AppIntroBaseFragment.onCreateView(SourceFile:1)
	at androidx.fragment.app.Fragment.performCreateView(SourceFile:4)
```

**Comment by cortinico** [comment]
Thanks for your report @KaanRF 

I've done a quick search, and I wasn't able to find any of the mentioned Non-SDK API: `FontFamily`, `makeOptionalFitsSystemWindows`.

For the `makeOptionalFitsSystemWindows` seems like the method is actually used by AndroidX:
https://stackoverflow.com/questions/52358496/setcontentview-is-using-non-sdk-interface

Happy to get further input if someone wants to investigate.

**Comment by sampurna-kumari** [comment]
Hi, I would like to work on this issue. Can you please assign it to me? @cortinico
