### ISSUE TITLE
Getting "layout/appintro_intro_layout: Binary XML file line #48: You must supply a layout_width attribute" error when trying to implement AppIntro library.

### ISSUE THREAD

**Issue by Palle-Hansen** [AppIntro/AppIntro#967]
## 🐛 Describe the bug

I implemented the library as per the readme file, I made sure not to call setContentView in the AppIntro activity, and i've checked that all the necessary dependencies are included in my project. Nevertheless, everytime I launch the app, it crashes on startup saying: "layout/appintro_intro_layout: Binary XML file line #48: You must supply a layout_width attribute". Might this be an issue related to the androidx migration, or is it something else you might know about? I've already successfully implemented the library on a test application, so dont know what I might be doing wrong. It is a work related project, why i'm not really at liberty to share any code (stack trace added though).. =(

## ⚠️ Current behavior

The app crashes saying: "layout/appintro_intro_layout: Binary XML file line #48: You must supply a layout_width attribute"

## ✅ Expected behavior

I expected the "AppIntroActivity" to launch without problems (started from MainActivity -> onCreate). The contents of the "AppIntroActivity" activity is basically copy/pasted from the readme file to test implementation, so there should'nt be anything wrong with the code in the AppIntro part.

## 💣 Steps to reproduce

No idea, because the root cause of the problem eludes me.

## 📑 Your Code

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.motinno.singletracker.beta, PID: 13552
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.motinno.singletracker.beta/com.motinno.singletracker.activities.AppIntroActivity}: android.view.InflateException: Binary XML file line #48 in com.motinno.singletracker.beta:layout/appintro_intro_layout: Binary XML file line #48: You must supply a layout_width attribute.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: android.view.InflateException: Binary XML file line #48 in com.motinno.singletracker.beta:layout/appintro_intro_layout: Binary XML file line #48: You must supply a layout_width attribute.
     Caused by: java.lang.UnsupportedOperationException: Binary XML file line #48: You must supply a layout_width attribute.
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:830)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:9255)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:9453)
        at androidx.constraintlayout.widget.ConstraintLayout$LayoutParams.<init>(ConstraintLayout.java:2902)
        at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:1934)
        at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:486)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.github.appintro.AppIntroBase.onCreate(AppIntroBase.kt:396)
        at com.motinno.singletracker.activities.AppIntroActivity.onCreate(AppIntroActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

## 📱 Tech info
 - AppIntro Version: 6.1.0
 - Device: any
 - Android OS Version: 11

**Comment by cortinico** [comment]
It's impossible to fully debug this without the code or a reproducer.

What I think is happening is something related to styles/themes of your host application.
Specifically the app is crashing as the element at line `appintro_intro_layout:48` is missing the `layout_width`.

Ideally you can try to add this to your styles:

```
    <style name="AppIntroButtonStyleCompat">
        <item name="android:background">?attr/selectableItemBackground</item>
        <item name="android:minHeight">@dimen/appintro_button_minheight</item>
        <item name="android:minWidth">@dimen/appintro_button_minwidth</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_margin">@dimen/appintro_button_margin</item>
    </style>
```

You need a bit of trial an error as it can be that it crashes at another line after you add this.

**Comment by Palle-Hansen** [comment]
I've resolved the issue: On further inspection, it turns out that the library had actually been implemented before, with the dependency 'com.github.apl-devs:appintro:v4.2.3'. Removing this fixed the problem, and it's running as expected now. Sorry for the inconvenience, I'm fairly new to the codebase, and it is a messy one unfortunately, so had'nt noticed.
Good work on the library, and thanks for replying =)
